### ISSUE TITLE
Retorno false ao tentar enviar a mensagem

### ISSUE THREAD

**Issue by kkkasio** [IuriKintschev/bot-api#1]
Olá!
Quando enviado a solicitação para a rota de enviar a mensagem ,a mesma não é enviada!
já verifiquei que dentro do **req.client** tenho a instância do Wpp(Venon)!

**Comment by IuriKintschev** [comment]
Opa, então amigo. Esse projeto foi realizado por causa de um hackathon, esta retornando falso porque antes de mandar a mensagem o bot vai mandar uma requisição para uma segunda API com uma base de dados com numeros cadastrados.
Então a ideia é so conseguir mandar mensagem e o bot consversar com os numeros que estao nessa segunda API.
Vc pode retirar essa validação e utilizar, ou desenvolver um novo bot com a lib que eu utilizei https://www.npmjs.com/package/venom-bot

**Comment by IuriKintschev** [comment]
Como esta encaminhando o numero ?
ele precisa do 55ddd e tbm precisa do numero com o 9 digito

**Comment by IuriKintschev** [comment]
Desculpe havia informado errado, a tal verificação que mencionei so ocorre na API do whatsapp em bot-api/src/whatsapp/controllers/messagesController.js , é realizado uma chamada a outra API para verificar o numero, ai o bot so responde quem tiver cadastrado nela, so remover que ela devera funcionar normalmente.

**Comment by IuriKintschev** [comment]
Na rota para encaminhar a mensagem deveria estar funcionando normalmente, o corpo deve ser como esse
POST/send
    {
        "phone": "5566999999999",
        "body": "Hello World"
    }
